name: example
description: Example app for flutter_form_builder package
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_localizations:
    sdk: flutter
  intl: ">=0.20.0 <0.21.0"
  geolocator: ^11.0.0
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  qr_flutter: ^4.1.0
  print_bluetooth_thermal: ^1.1.3
  esc_pos_utils_plus: ^2.0.3
  permission_handler: ^11.3.1
  mobile_scanner: ^6.0.4
  http: ^1.6.0
  provider: ^6.1.2
  qr_code_scanner: ^0.4.0
  pdf: ^3.10.0
  printing: ^5.11.0

  # ✅ ใช้ชุดนี้ครับ (Image V4 + Zxing)
  
  zxing_scanner: ^1.0.0
  zxing_lib: ^1.1.4
  image: 4.5.4

dev_dependencies:
  flutter_lints: ">=6.0.0"
  flutter_test:
    sdk: flutter

  # ✅ อัปเกรดตัวนี้เป็น 0.14.4 (เพื่อให้เข้ากับ image 4.2.0)
  flutter_launcher_icons: ^0.14.4
 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png

  # แนะนำสำหรับ Android Adaptive Icon
  #adaptive_icon_foreground: assets/icons/app_icon_fg.png  # ถ้าไม่มี ให้ลบ 2 บรรทัด adaptive ออก
  #daptive_icon_background: "#FFFFFF"                     # หรือใส่ไฟล์ภาพพื้นหลังแทนก็ได้

  # สำหรับ Android 13+ (Monochrome icon บนธีมขาวดำ)
  #adaptive_icon_monochrome: assets/icons/app_icon_mono.png  # ถ้าไม่มี ให้ลบออกได้


flutter:
  uses-material-design: true
  assets:
    - assets/top_login.png
    - assets/bottom_login.png
    - assets/mccc.png
    - assets/leaf.png
    - assets/bottom_menu.png
    - assets/top_menu.png
    - assets/fonts/NotoSansThai-Regular.ttf  # +++ add: Thai TTF for printing
    - assets/fonts/NotoSansThai-Regular.zip     # สำหรับ BitmapFont image.drawString
  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf